name: foxid
version: 1.2.2
description: A library for manipulating with FOxID - unique identifiers with the possibility of lexicographic sorting.
repository: https://git.kasefuchs.su/foxcordchat/foxid
issue_tracker: https://github.com/foxcordchat/foxid/issues

environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  base32: ^2.1.3

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
